version: '3'
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - /home/sunthar/mosquitto/config:/mosquitto/config
      - /home/sunthar/mosquitto/data:/mosquitto/data
      - /home/sunthar/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"


